#ifndef __TCGUIDS_H__
#define __TCGUIDS_H__

// See Bug O11 56010
// See header comments in %otools%\inc\misc\tcoinuse.txt
// See ShowUsage text in  %otools%\bin\gimmebuild.bat

#if DEBUG
#define O9_CATEGORY_GUID_CORE_OFFICE "{D304E920-A68A-11d1-B5B5-106097C998E7}"
#else
#define O9_CATEGORY_GUID_CORE_OFFICE "{D304E920-A68A-11d1-B5B5-006097C998E7}"
#endif

#if DEBUG
#define O10_CATEGORY_GUID_CORE_OFFICE "{EAD07EA6-F176-11D3-8D33-1050048381D3}"
#else
#define O10_CATEGORY_GUID_CORE_OFFICE "{EAD07EA6-F176-11D3-8D33-0050048381D3}"
#endif

#if DEBUG
#define O11_CATEGORY_GUID_CORE_OFFICE "{BC174BAD-2F53-4855-A1D5-1D575C19B1EA}"
#define O11_CATEGORY_GUID_CORE_OFFICE_W L"{BC174BAD-2F53-4855-A1D5-1D575C19B1EA}"
#else
#define O11_CATEGORY_GUID_CORE_OFFICE "{BC174BAD-2F53-4855-A1D5-0D575C19B1EA}"
#define O11_CATEGORY_GUID_CORE_OFFICE_W L"{BC174BAD-2F53-4855-A1D5-0D575C19B1EA}"
#endif

#define VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE O11_CATEGORY_GUID_CORE_OFFICE
#define VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE_W O11_CATEGORY_GUID_CORE_OFFICE_W

// Access
#define VERSION_DEPENDENT_CATEGORY_GUID_ACCESS_EXE VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE

// Excel
#define VERSION_DEPENDENT_CATEGORY_GUID_EXCEL_EXE VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE

// Frontpage
#define VERSION_DEPENDENT_CATEGORY_GUID_FRONTPAGE_EXE VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE

// Mso
#define VERSION_DEPENDENT_CATEGORY_GUID_MSO_DLL VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE
#define VERSION_DEPENDENT_CATEGORY_GUID_MSO_DLL_W VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE_W

// MsoAuth
#define VERSION_DEPENDENT_CATEGORY_GUID_MSOAUTH_DLL VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE
#define VERSION_DEPENDENT_CATEGORY_GUID_MSOAUTH_DLL_W VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE_W

// MsoSV
#define VERSION_DEPENDENT_CATEGORY_GUID_MSOSV_DLL VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE
#define VERSION_DEPENDENT_CATEGORY_GUID_MSOSV_DLL_W VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE_W

// Osa
#define VERSION_DEPENDENT_CATEGORY_GUID_OSA_EXE VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE

// Outlook
#define VERSION_DEPENDENT_CATEGORY_GUID_OUTLOOK_EXE VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE

// Powerpoint
#define VERSION_DEPENDENT_CATEGORY_GUID_POWERPOINT_EXE VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE

// Project
#define VERSION_DEPENDENT_CATEGORY_GUID_PROJECT_EXE VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE

// Publisher
#define VERSION_DEPENDENT_CATEGORY_GUID_PUBLISHER_EXE VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE

// Stemmer
#define VERSION_DEPENDENT_CATEGORY_GUID_STEMMER_DLL O10_CATEGORY_GUID_CORE_OFFICE

// Visio
#define VERSION_DEPENDENT_CATEGORY_GUID_VISIO_EXE {13FA8779-9C5F-4288-A1BF-F7E4246A22C6}

// Word
#define VERSION_DEPENDENT_CATEGORY_GUID_WORD_EXE VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE

// WordBreakCht
#define VERSION_DEPENDENT_CATEGORY_GUID_WORDBREAKCHT VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE
#define VERSION_DEPENDENT_CATEGORY_GUID_WORDBREAKCHT_W VERSION_DEPENDENT_CATEGORY_GUID_CORE_OFFICE_W

#endif /* __TCGUIDS_H__ */
